// Build a classic-script highlight.js bundle for the renderer.
//
// The website loads highlight.min.js + atom-one-dark from cdnjs. We can't:
// the renderer runs from file:// under a CSP that blocks remote script, and a
// file:// page can't load ES modules either (Chromium refuses the cross-origin
// request), so the package's es/ build is unusable as-is. The npm package ships
// only CommonJS (lib/) and ESM (es/) — no browser bundle — so this generates
// one: core + the same language set the CDN's "common" build carries, wrapped
// in a tiny module shim and assigned to window.hljs.
//
// The language list is READ FROM lib/common.js rather than hard-coded, so this
// tracks whatever the pinned highlight.js version considers common and stays in
// step with what the website's CDN bundle highlights.
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const OUT_DIR = path.join(ROOT, 'src', 'renderer', 'vendor');
const PKG_DIR = path.join(ROOT, 'node_modules', 'highlight.js');

function main() {
    fs.mkdirSync(OUT_DIR, { recursive: true });

    if (!fs.existsSync(path.join(PKG_DIR, 'package.json'))) {
        console.warn('[vendor] highlight.js not installed yet — skipping.');
        return;
    }
    const version = JSON.parse(fs.readFileSync(path.join(PKG_DIR, 'package.json'), 'utf8')).version;

    // hljs.registerLanguage('name', require('./languages/file'));
    const common = fs.readFileSync(path.join(PKG_DIR, 'lib', 'common.js'), 'utf8');
    const langs = [];
    const re = /registerLanguage\('([^']+)',\s*require\('\.\/languages\/([^']+)'\)\)/g;
    let m;
    // The requires are extensionless (require('./languages/xml')).
    while ((m = re.exec(common)) !== null) {
        langs.push({ name: m[1], file: /\.js$/.test(m[2]) ? m[2] : m[2] + '.js' });
    }
    if (!langs.length) {
        console.error('[vendor] could not read the language list out of highlight.js/lib/common.js');
        process.exitCode = 1;
        return;
    }

    const core = fs.readFileSync(path.join(PKG_DIR, 'lib', 'core.js'), 'utf8');
    // core.js is a self-contained rollup bundle and the language files are leaf
    // modules — none of them require() anything else, which is what makes a
    // three-line module shim enough. Verify rather than assume.
    for (const src of [core]) {
        if (/\brequire\s*\(/.test(src)) {
            console.error('[vendor] highlight.js core now has require() calls — the module shim needs updating.');
            process.exitCode = 1;
            return;
        }
    }

    const out = [];
    out.push('// GENERATED by scripts/vendor-hljs.js — do not edit.');
    out.push(`// highlight.js ${version}, core + ${langs.length} common languages.`);
    out.push('(function (global) {');
    out.push('    var __m = {};');
    out.push('    function __def(id, fn) { __m[id] = { fn: fn, mod: null }; }');
    out.push('    function __req(id) {');
    out.push('        var e = __m[id];');
    out.push('        if (!e) throw new Error("hljs bundle: missing module " + id);');
    out.push('        if (!e.mod) { e.mod = { exports: {} }; e.fn(e.mod, e.mod.exports); }');
    out.push('        return e.mod.exports;');
    out.push('    }');

    const wrap = (id, src) =>
        `    __def(${JSON.stringify(id)}, function (module, exports) {\n${src}\n    });`;

    out.push(wrap('core', core));
    for (const l of langs) {
        const src = fs.readFileSync(path.join(PKG_DIR, 'lib', 'languages', l.file), 'utf8');
        if (/\brequire\s*\(/.test(src)) {
            console.error(`[vendor] language ${l.name} has require() calls — the module shim needs updating.`);
            process.exitCode = 1;
            return;
        }
        out.push(wrap('lang/' + l.name, src));
    }

    out.push('    var hljs = __req("core");');
    for (const l of langs) {
        out.push(`    hljs.registerLanguage(${JSON.stringify(l.name)}, __req(${JSON.stringify('lang/' + l.name)}));`);
    }
    out.push('    global.hljs = hljs;');
    out.push('})(typeof window !== "undefined" ? window : this);');

    const dest = path.join(OUT_DIR, 'hljs.js');
    fs.writeFileSync(dest, out.join('\n'), 'utf8');

    // Same theme the website pulls from the CDN, so highlighted code looks the
    // same in both clients.
    const theme = path.join(PKG_DIR, 'styles', 'atom-one-dark.min.css');
    fs.copyFileSync(theme, path.join(OUT_DIR, 'hljs-theme.css'));

    const kb = Math.round(fs.statSync(dest).size / 1024);
    console.log(`[vendor] highlight.js ${version} -> hljs.js (${langs.length} languages, ${kb} KB) + atom-one-dark`);
}

main();
